name: lezer-webpack-loader

on:
  # Manual trigger
  workflow_dispatch:

  # When a commit is pushed
  push:

permissions:
  contents: read # To clone the repository

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install the dependencies
        run: npm ci

      - name: Check the format
        run: npm run format

      - name: Lint the package
        run: npm run lint

      - name: Test the package
        run: npm run test

      - name: Build the package
        run: npm run build
